// Generated from the web's components/settings/settings-search-index.ts.
// Keep in step with the web when it adds or renames a setting.

/// One searchable setting: the panel it lives in, its visible label (also the
/// row the search jumps to) and lowercase synonyms.
struct SettingsField {
    let panel: String
    let label: String
    let keywords: [String]
}

let settingsFieldIndex: [SettingsField] = [
    SettingsField(panel: "about", label: "Copy info", keywords: ["bug report", "build", "clipboard", "commit", "diagnostics", "version"]),
    SettingsField(panel: "appearance", label: "Coverage rails", keywords: ["bar", "checkmark", "current", "dot", "fill", "glow", "library rail", "rail style", "trailing dot"]),
    SettingsField(panel: "appearance", label: "Consolidate HD + 4K", keywords: ["combine", "combo rail", "hd 4k", "merge", "single rail", "uhd"]),
    SettingsField(panel: "about", label: "Project links", keywords: ["changelog", "documentation", "github", "releases", "repo", "report an issue"]),
    SettingsField(panel: "access", label: "Add user", keywords: ["account", "create user", "login", "new user", "principal", "rbac"]),
    SettingsField(panel: "access", label: "Administrator", keywords: ["admin", "full access", "privilege", "role", "superuser"]),
    SettingsField(panel: "access", label: "Manage access", keywords: ["grant", "instance access", "per-instance", "permission", "rbac", "revoke"]),
    SettingsField(panel: "access", label: "Password", keywords: ["credential", "login", "passphrase", "secret"]),
    SettingsField(panel: "access", label: "Username", keywords: ["account name", "login", "signin", "user"]),
    SettingsField(panel: "clients", label: "Add client", keywords: ["add", "create", "new download client", "qbit", "sab"]),
    SettingsField(panel: "clients", label: "Advanced", keywords: ["expand", "extra settings", "hidden", "more options"]),
    SettingsField(panel: "clients", label: "Anime", keywords: ["anime category", "fansub", "label", "path"]),
    SettingsField(panel: "clients", label: "API Key", keywords: ["auth", "sab key", "secret", "token", "x-api-key"]),
    SettingsField(panel: "clients", label: "Client priority", keywords: ["first choice", "last resort", "ordering", "protocol priority", "rank"]),
    SettingsField(panel: "clients", label: "Download Clients", keywords: ["debrid", "decypharr", "qbittorrent", "rdt-client", "sabnzbd", "torrent", "usenet"]),
    SettingsField(panel: "clients", label: "Enabled", keywords: ["active", "disable", "off", "on", "toggle"]),
    SettingsField(panel: "clients", label: "Host", keywords: ["address", "hostname", "ip", "server", "url"]),
    SettingsField(panel: "clients", label: "Movies", keywords: ["label", "movie category", "path", "radarr category"]),
    SettingsField(panel: "clients", label: "Name", keywords: ["client name", "label", "title"]),
    SettingsField(panel: "clients", label: "Older Priority", keywords: ["back catalog", "old releases", "queue priority", "sab priority"]),
    SettingsField(panel: "clients", label: "Password", keywords: ["credentials", "login", "qbit password", "secret"]),
    SettingsField(panel: "clients", label: "Port", keywords: ["8080", "8282", "connection", "network port"]),
    SettingsField(panel: "clients", label: "Post-import category", keywords: ["after import", "move category", "qbit category", "seeding", "torrent"]),
    SettingsField(panel: "clients", label: "Recent Priority", keywords: ["aired", "new", "queue priority", "recent download", "sab priority"]),
    SettingsField(panel: "clients", label: "Remove completed", keywords: ["cleanup", "delete after import", "history", "purge"]),
    SettingsField(panel: "clients", label: "Remove failed", keywords: ["cleanup", "delete failed", "history", "purge"]),
    SettingsField(panel: "clients", label: "Series", keywords: ["label", "path", "sonarr category", "tv category"]),
    SettingsField(panel: "clients", label: "SSL", keywords: ["encryption", "https", "secure", "tls", "use ssl"]),
    SettingsField(panel: "clients", label: "Test", keywords: ["check", "connected", "connection test", "probe", "verify"]),
    SettingsField(panel: "clients", label: "URL Base", keywords: ["base path", "path prefix", "reverse proxy", "sabnzbd prefix"]),
    SettingsField(panel: "clients", label: "Username", keywords: ["account", "login", "qbit user", "user"]),
    SettingsField(panel: "connect", label: "Add notification", keywords: ["add", "create", "discord", "new agent", "telegram", "webhook"]),
    SettingsField(panel: "connect", label: "arr webhooks", keywords: ["arr connect", "connect notification", "integration", "radarr webhook", "sonarr webhook"]),
    SettingsField(panel: "connect", label: "Bot token", keywords: ["api token", "credentials", "secret", "telegram token"]),
    SettingsField(panel: "connect", label: "Chat ID", keywords: ["channel id", "group id", "recipient", "telegram chat"]),
    SettingsField(panel: "connect", label: "Enable", keywords: ["active", "disable", "off", "on", "toggle"]),
    SettingsField(panel: "connect", label: "Enabled", keywords: ["disable agent", "fire", "off", "on", "toggle"]),
    SettingsField(panel: "connect", label: "Name", keywords: ["agent name", "label", "title"]),
    SettingsField(panel: "connect", label: "Notifications", keywords: ["agents", "alerts", "connect", "discord", "telegram", "webhook"]),
    SettingsField(panel: "connect", label: "On download failed", keywords: ["download error", "error", "event", "grab failed"]),
    SettingsField(panel: "connect", label: "On grab", keywords: ["download started", "event", "release grabbed", "sent to client"]),
    SettingsField(panel: "connect", label: "On import", keywords: ["event", "file added", "imported", "library"]),
    SettingsField(panel: "connect", label: "On manual import required", keywords: ["event", "import failed", "manual review", "needs attention"]),
    SettingsField(panel: "connect", label: "On request", keywords: ["available", "discord request", "event", "new request", "request made", "requested"]),
    SettingsField(panel: "connect", label: "On upgrade", keywords: ["better release", "event", "quality upgrade", "replaced"]),
    SettingsField(panel: "connect", label: "Test", keywords: ["notification test", "probe", "send test", "verify"]),
    SettingsField(panel: "connect", label: "URL", keywords: ["http url", "post url", "target", "webhook endpoint"]),
    SettingsField(panel: "connect", label: "Webhook URL", keywords: ["discord webhook", "endpoint", "hook", "incoming url"]),
    SettingsField(panel: "database", label: "Migrate to Postgres", keywords: ["backend", "cutover", "migration", "pg", "postgresql", "sqlite", "wizard"]),
    SettingsField(panel: "defaultprofiles", label: "Minimum availability", keywords: ["announced", "home media", "in cinemas", "movie gate", "radarr", "released"]),
    SettingsField(panel: "defaultprofiles", label: "Quality profile", keywords: ["add flow", "default profile", "import", "kind tier", "matrix", "smart default"]),
    SettingsField(panel: "defaultprofiles", label: "Root folder", keywords: ["add flow", "default path", "destination", "directory", "kind tier"]),
    SettingsField(panel: "defaultprofiles", label: "Save defaults", keywords: ["apply", "commit", "matrix", "persist", "save"]),
    SettingsField(panel: "versions", label: "Add edition", keywords: ["aliases", "canonical name", "create edition", "director's cut", "imax", "new cut"]),
    SettingsField(panel: "versions", label: "Aliases", keywords: ["alternate names", "parser match", "spellings", "synonyms", "tags"]),
    SettingsField(panel: "versions", label: "Editions", keywords: ["cut", "director's cut", "edition vocabulary", "extended", "imax", "open matte", "theatrical"]),
    SettingsField(panel: "experimental", label: "Condemned-title cool-off", keywords: ["backoff", "condemn", "cooldown", "rest", "rotation", "seconds"]),
    SettingsField(panel: "experimental", label: "Failed-grab cool-off schedule", keywords: ["backoff", "cooldown", "escalating", "failed grab", "retry schedule", "seconds list"]),
    SettingsField(panel: "experimental", label: "Rapid-failure guard", keywords: ["burst", "failures", "settle", "threshold", "throttle"]),
    SettingsField(panel: "experimental", label: "Retry pacing", keywords: ["backoff", "interval", "min interval", "seconds", "slot", "throttle"]),
    SettingsField(panel: "experimental", label: "Smarter automatic searches", keywords: ["anti-thrash", "auto search", "beta", "indexer priority", "replacement search", "retry"]),
    SettingsField(panel: "experimental", label: "Usenet retry budget", keywords: ["copies", "cross-indexer", "grab attempts", "nzb", "retry"]),
    SettingsField(panel: "filemanagement", label: "Analyse video files", keywords: ["audio", "codec", "ffprobe", "hdr", "mediainfo", "probe", "scan"]),
    SettingsField(panel: "filemanagement", label: "Background sweep", keywords: ["broken symlink", "dead links", "decypharr", "reconcile", "self-heal", "sweep"]),
    SettingsField(panel: "filemanagement", label: "Clean up dead links", keywords: ["auto clean", "broken symlink", "delete dead", "movies series anime", "per kind", "self-heal"]),
    SettingsField(panel: "filemanagement", label: "Confirmation scans", keywords: ["confirm", "consecutive", "dangling", "min scans", "self-heal", "threshold"]),
    SettingsField(panel: "filemanagement", label: "Default import mode", keywords: ["copy", "debrid", "hardlink", "move", "new roots", "symlink"]),
    SettingsField(panel: "filemanagement", label: "Extra file extensions", keywords: ["comma-separated", "companion", "nfo", "srt", "sub", "subtitles"]),
    SettingsField(panel: "filemanagement", label: "Grace period", keywords: ["convergence", "dangling", "hours", "self-heal", "wait", "window"]),
    SettingsField(panel: "filemanagement", label: "Import extra files", keywords: ["companion files", "metadata", "nfo", "sidecar", "srt", "subtitles"]),
    SettingsField(panel: "filemanagement", label: "Media analysis timeout", keywords: ["cold mount", "debrid", "ffprobe", "mediainfo", "probe timeout", "seconds"]),
    SettingsField(panel: "filemanagement", label: "Minimum free space", keywords: ["disk space", "free space", "guard", "import block", "mb", "threshold"]),
    SettingsField(panel: "filemanagement", label: "Outage fraction", keywords: ["fraction", "mount outage", "proportion", "ratio", "self-heal", "stand down"]),
    SettingsField(panel: "filemanagement", label: "Outage minimum count", keywords: ["dangling", "files", "mount outage", "self-heal", "stand down", "threshold"]),
    SettingsField(panel: "filemanagement", label: "Probe timeout", keywords: ["dangling", "per file", "seconds", "self-heal", "stat timeout", "target read"]),
    SettingsField(panel: "filemanagement", label: "Probe workers", keywords: ["concurrency", "parallel", "probes", "self-heal", "threads", "workers"]),
    SettingsField(panel: "filemanagement", label: "Propers & repacks", keywords: ["do not prefer", "prefer", "proper", "repack", "trash", "upgrade"]),
    SettingsField(panel: "filemanagement", label: "Recycle bin", keywords: ["deleted files", "path", "permanent delete", "recover", "recycle", "trash"]),
    SettingsField(panel: "filemanagement", label: "Recycle bin cleanup", keywords: ["auto delete", "cleanup", "days", "purge", "retention", "trash"]),
    SettingsField(panel: "filemanagement", label: "Rejected file extensions", keywords: ["block", "exe", "iso", "lnk", "reject import", "unwanted file"]),
    SettingsField(panel: "filemanagement", label: "Corrupt / incomplete file at import", keywords: ["corrupt", "incomplete", "truncated", "broken", "ffprobe", "invalid", "hold", "blocklist", "delete research", "obfuscated", "decode"]),
    SettingsField(panel: "filemanagement", label: "Retry failed analysis", keywords: ["backlog", "mediainfo", "re-analyse", "re-probe", "requeue", "retry"]),
    SettingsField(panel: "filemanagement", label: "Search after loss", keywords: ["auto search", "dead file", "per kind", "re-search", "replace", "self-heal"]),
    SettingsField(panel: "filemanagement", label: "Sweep interval", keywords: ["cadence", "dead link", "frequency", "hours", "reconcile", "self-heal"]),
    SettingsField(panel: "filemanagement", label: "Verify resolution from probe", keywords: ["4k to 1080p", "correct quality", "downscale", "mediainfo", "pixels", "resolution"]),
    SettingsField(panel: "formats", label: "Browse TRaSH catalog", keywords: ["browse", "catalog", "import cf", "presets", "trash guides"]),
    SettingsField(panel: "formats", label: "Conditions", keywords: ["and or", "condition block", "match", "regex", "release title", "spec", "specifications"]),
    SettingsField(panel: "formats", label: "Custom format name", keywords: ["cf name", "label", "rename", "title"]),
    SettingsField(panel: "formats", label: "Filter by kind", keywords: ["anime", "media kind", "movie", "series", "tag"]),
    SettingsField(panel: "formats", label: "Filter by provenance", keywords: ["arr", "chip", "manual", "origin", "preset", "source", "trash"]),
    SettingsField(panel: "formats", label: "Import", keywords: ["arr", "capture", "import cf", "preset", "radarr", "sonarr"]),
    SettingsField(panel: "formats", label: "Include when renaming", keywords: ["filename", "include_when_renaming", "rename", "renaming token", "tag"]),
    SettingsField(panel: "formats", label: "Kind", keywords: ["anime", "media kind", "movie", "series", "type"]),
    SettingsField(panel: "formats", label: "Live test", keywords: ["check", "interactive", "match", "release title", "score", "tester"]),
    SettingsField(panel: "formats", label: "New format", keywords: ["+ new", "add", "create", "custom format"]),
    SettingsField(panel: "formats", label: "Search formats", keywords: ["custom format", "filter", "find", "lookup", "name"]),
    SettingsField(panel: "general", label: "About", keywords: ["app version", "build", "info", "release", "version"]),
    SettingsField(panel: "general", label: "Actively probe for 4K", keywords: ["2160p", "active", "check 4k", "discovery probe", "indexer queries", "uhd"]),
    SettingsField(panel: "general", label: "Advanced download handling", keywords: ["disclosure", "grace", "queue", "stuck", "timeout", "vanished"]),
    SettingsField(panel: "general", label: "Automatic cutoff-unmet search", keywords: ["auto upgrade", "cutoff", "quality upgrade", "re-search", "unmet", "upgrade"]),
    SettingsField(panel: "general", label: "Cutoff items per run", keywords: ["backlog", "batch", "cap", "cutoff", "limit", "per sweep", "upgrade search"]),
    SettingsField(panel: "general", label: "Retry recent grabs for an upgrade", keywords: ["active upgrade", "auto upgrade", "post-grab", "recent", "retry", "rss miss", "upgrade"]),
    SettingsField(panel: "general", label: "Recent window", keywords: ["active upgrade", "days", "recent", "retry window", "upgrade window"]),
    SettingsField(panel: "general", label: "Automatic missing search", keywords: ["auto search", "backlog", "missing", "monitored", "wanted"]),
    SettingsField(panel: "general", label: "Availability delay", keywords: ["days", "movie available", "physical release", "release date", "search after", "search before"]),
    SettingsField(panel: "general", label: "Default calendar view", keywords: ["agenda", "calendar layout", "day", "forecast", "month", "week"]),
    SettingsField(panel: "general", label: "Enable animations", keywords: ["accessibility", "framer", "motion", "reduce-motion", "reduced motion", "transitions"]),
    SettingsField(panel: "general", label: "First day of week", keywords: ["calendar", "day", "monday", "sunday", "week start"]),
    SettingsField(panel: "general", label: "fusionha API key", keywords: ["api", "credentials", "external tools", "regenerate", "reveal", "token", "x-api-key"]),
    SettingsField(panel: "general", label: "Items per run", keywords: ["backlog", "batch", "cap", "limit", "missing search", "per sweep"]),
    SettingsField(panel: "general", label: "Keep 4K sightings fresh for (days)", keywords: ["2160p", "available tab", "expire", "freshness", "staleness", "uhd"]),
    SettingsField(panel: "general", label: "Observe 4K availability", keywords: ["2160p", "discovery", "learn 4k", "observer", "sightings", "uhd"]),
    SettingsField(panel: "general", label: "Playful voice", keywords: ["characterful", "microcopy", "neutral", "text", "tone", "wording"]),
    SettingsField(panel: "general", label: "Probe interval (seconds)", keywords: ["4k probe", "cadence", "discovery", "indexer ban", "seconds", "sweep frequency"]),
    SettingsField(panel: "general", label: "Re-grab cooldown", keywords: ["blocklist", "excluded", "re-grab", "removed release", "retry", "thrash"]),
    SettingsField(panel: "general", label: "Real integrations", keywords: ["download client", "indexer", "live", "mock", "stub", "test mode"]),
    SettingsField(panel: "general", label: "RSS interval", keywords: ["cadence", "feed", "indexer ban", "poll", "rss sync", "sync frequency"]),
    SettingsField(panel: "general", label: "Search interval", keywords: ["backlog", "cadence", "cutoff", "missing search", "seconds", "sweep frequency", "unmet", "upgrade search", "wanted"]),
    SettingsField(panel: "general", label: "Search on add", keywords: ["add title", "auto search", "grab on add", "immediate search", "on add"]),
    SettingsField(panel: "general", label: "Season episode-search interval", keywords: ["episode", "gradual", "per-episode search", "seconds", "spaced out", "split button"]),
    SettingsField(panel: "general", label: "Setup wizard", keywords: ["first run", "getting started", "import", "onboarding", "re-run", "welcome"]),
    SettingsField(panel: "general", label: "Stalled display threshold", keywords: ["0%", "display", "frozen", "minutes", "queue", "stalled flag"]),
    SettingsField(panel: "general", label: "Stalled download timeout", keywords: ["abandon", "failed", "queue", "re-search", "stalled", "timeout"]),
    SettingsField(panel: "general", label: "Titles per probe run", keywords: ["4k probe", "batch", "cap", "discovery", "limit", "per sweep"]),
    SettingsField(panel: "general", label: "Vanished download grace", keywords: ["failed", "minutes", "missing download", "queue", "re-search", "removed"]),
    SettingsField(panel: "general", label: "Week card style", keywords: ["calendar event", "compact", "landscape", "portrait", "poster", "tier accent"]),
    SettingsField(panel: "indexers", label: "Add indexer", keywords: ["add", "create", "new indexer", "newznab", "torznab"]),
    SettingsField(panel: "indexers", label: "Anime Categories", keywords: ["5070", "anime category ids", "fansub", "release group"]),
    SettingsField(panel: "indexers", label: "Anime Standard Format Search", keywords: ["absolute episode", "anime search", "fansub", "standard numbering"]),
    SettingsField(panel: "indexers", label: "API key", keywords: ["auth", "credentials", "secret", "token", "x-api-key"]),
    SettingsField(panel: "indexers", label: "API path", keywords: ["/api", "endpoint path", "route", "torznab path"]),
    SettingsField(panel: "indexers", label: "Base URL", keywords: ["api url", "endpoint", "host", "server address", "url"]),
    SettingsField(panel: "indexers", label: "Categories", keywords: ["2000", "5000", "category ids", "filter", "newznab categories"]),
    SettingsField(panel: "indexers", label: "Daily discovery query cap", keywords: ["4k discovery", "cap", "daily limit", "probe budget", "queries per day"]),
    SettingsField(panel: "indexers", label: "Enable", keywords: ["active", "disable", "master toggle", "off", "on"]),
    SettingsField(panel: "indexers", label: "Enable Automatic Search", keywords: ["auto search", "automatic", "grab", "rss search"]),
    SettingsField(panel: "indexers", label: "Enable Interactive Search", keywords: ["interactive", "manual search", "on-demand", "user search"]),
    SettingsField(panel: "indexers", label: "Enable RSS", keywords: ["automatic", "feed", "monitoring", "rss sync"]),
    SettingsField(panel: "indexers", label: "Indexers", keywords: ["newznab", "prowlarr", "search source", "torrent", "torznab", "trackers", "usenet"]),
    SettingsField(panel: "indexers", label: "Min query interval (s)", keywords: ["cooldown", "query cap", "rate limit", "seconds", "throttle"]),
    SettingsField(panel: "indexers", label: "Minimum age (min)", keywords: ["delay", "hold release", "propagation", "retention", "usenet age"]),
    SettingsField(panel: "indexers", label: "Minimum seeders", keywords: ["health", "min seeds", "peers", "torrent seeders"]),
    SettingsField(panel: "indexers", label: "Name", keywords: ["indexer name", "label", "title"]),
    SettingsField(panel: "indexers", label: "Priority", keywords: ["order", "preference", "ranking", "weight"]),
    SettingsField(panel: "indexers", label: "Protocol", keywords: ["newznab", "torrent", "torznab", "type", "usenet"]),
    SettingsField(panel: "indexers", label: "Seed ratio", keywords: ["seeding", "share ratio", "torrent ratio", "upload"]),
    SettingsField(panel: "indexers", label: "Seed time (min)", keywords: ["minutes", "seeding time", "torrent seed", "upload duration"]),
    SettingsField(panel: "indexers", label: "Test", keywords: ["check", "connection test", "probe", "verify"]),
    SettingsField(panel: "indexers", label: "Test all", keywords: ["bulk test", "check all", "probe all", "test every indexer"]),
    SettingsField(panel: "indexers", label: "Unlimited queries (probe freely)", keywords: ["4k probe", "budget", "discovery probe", "no cap", "unlimited"]),
    SettingsField(panel: "notifications", label: "Notifications", keywords: ["alerts", "apns", "banner", "ios", "pwa", "push", "vapid", "web push"]),
    SettingsField(panel: "notifications", label: "Enable on this device", keywords: ["device", "permission", "register", "subscribe", "turn on push"]),
    SettingsField(panel: "notifications", label: "Send test notification", keywords: ["banner", "check", "test push", "try"]),
    SettingsField(panel: "notifications", label: "Delivery", keywords: ["coalesce", "group by title", "grouping", "immediate"]),
    SettingsField(panel: "notifications", label: "Quiet hours", keywords: ["do not disturb", "dnd", "mute", "overnight", "silence"]),
    SettingsField(panel: "notifications", label: "iOS app push (APNs)", keywords: ["apns", "auth key", "bundle id", "key id", "p8", "team id"]),
    SettingsField(panel: "notifications", label: "Rotate keys", keywords: ["invalidate", "reset", "vapid", "re-subscribe"]),
    SettingsField(panel: "notifications", label: "Request available", keywords: ["fulfilled", "requestor", "requests"]),
    SettingsField(panel: "instances", label: "Copy key", keywords: ["clipboard", "copy api key", "paste", "token"]),
    SettingsField(panel: "instances", label: "Enable", keywords: ["arr api", "disable instance", "off", "on", "toggle"]),
    SettingsField(panel: "instances", label: "Regenerate key", keywords: ["invalidate", "new api key", "regenerate", "reset key", "rotate key"]),
    SettingsField(panel: "instances", label: "Reveal key", keywords: ["copy", "secret", "show api key", "unmask", "view key"]),
    SettingsField(panel: "instances", label: "Root folder", keywords: ["default root", "landing folder", "path mapping", "storage", "tier root"]),
    SettingsField(panel: "instances", label: "Connections", keywords: ["arr emulation", "overseerr", "prowlarr", "radarr-4k", "radarr-hd", "sonarr-4k", "sonarr-hd", "virtual instances"]),
    SettingsField(panel: "instances", label: "Add connection", keywords: ["create instance", "new arr instance", "new connection"]),
    SettingsField(panel: "instances", label: "Offer-only limits", keywords: ["allowed profiles", "allowed roots", "restrict", "scope down"]),
    SettingsField(panel: "instances", label: "API Tokens", keywords: ["mint token", "pat", "personal access token", "revoke token"]),
    SettingsField(panel: "appearance", label: "Login layout", keywords: ["centered", "form", "living logo", "sign-in", "split", "wizard"]),
    SettingsField(panel: "appearance", label: "Media morphs on the sign-in page", keywords: ["animation", "anime", "dragon", "film", "living logo", "login", "tv"]),
    SettingsField(panel: "appearance", label: "Login background", keywords: ["backdrop", "sign-in background", "wallpaper"]),
    SettingsField(panel: "appearance", label: "Show logo", keywords: ["branding", "login logo", "mark", "sign-in"]),
    SettingsField(panel: "appearance", label: "Show app name", keywords: ["branding", "login", "sign-in", "wordmark"]),
    SettingsField(panel: "appearance", label: "Show tagline", keywords: ["branding", "description", "login", "sign-in", "subtitle"]),
    SettingsField(panel: "metadata", label: "Active window", keywords: ["active series", "airing", "days", "metadata", "near air date", "window"]),
    SettingsField(panel: "metadata", label: "Active-series refresh interval", keywords: ["airing", "cadence", "fast sweep", "metadata", "recent series", "seconds"]),
    SettingsField(panel: "metadata", label: "Advanced cadences", keywords: ["advanced", "disclosure", "metadata refresh", "sweep", "timings"]),
    SettingsField(panel: "metadata", label: "Air-time refresh — default", keywords: ["air time", "default cadence", "fallback", "far off", "seconds", "tvmaze"]),
    SettingsField(panel: "metadata", label: "Air-time refresh — imminent", keywords: ["3 days", "air time", "cadence", "imminent", "tvmaze", "upcoming"]),
    SettingsField(panel: "metadata", label: "Air-time refresh — soon", keywords: ["14 days", "air time", "cadence", "soon", "tvmaze", "upcoming"]),
    SettingsField(panel: "metadata", label: "Auto-apply the fix", keywords: ["apply", "automatic", "numbering", "renumber", "tvmaze", "unambiguous"]),
    SettingsField(panel: "metadata", label: "Auto-detect mismatches", keywords: ["detect", "episode numbering", "mismatch", "numbering", "sweep", "tvmaze"]),
    SettingsField(panel: "metadata", label: "Connection", keywords: ["authenticate", "check", "probe key", "test", "tmdb", "tvdb", "verify"]),
    SettingsField(panel: "metadata", label: "Default provider", keywords: ["global default", "metadata provider", "per-series override", "series", "source"]),
    SettingsField(panel: "metadata", label: "Hybrid", keywords: ["chip", "per-field", "precedence", "primary", "promote", "source order"]),
    SettingsField(panel: "metadata", label: "Enrichment", keywords: ["air times", "last filled", "run now", "sync status", "timestamp", "tvmaze"]),
    SettingsField(panel: "metadata", label: "Episode-title watch interval", keywords: ["backoff", "episode title", "placeholder title", "seconds", "tba", "watch"]),
    SettingsField(panel: "metadata", label: "Exclude anime", keywords: ["absolute numbering", "anime", "ambiguous", "exclude", "numbering", "tvmaze"]),
    SettingsField(panel: "metadata", label: "Full refresh interval", keywords: ["artwork", "metadata", "refresh cadence", "runtime", "seconds", "sweep"]),
    SettingsField(panel: "metadata", label: "Search delay after air", keywords: ["air delay", "auto search", "grace", "minutes", "tvmaze", "wait after air"]),
    SettingsField(panel: "metadata", label: "TMDB API key", keywords: ["api", "credentials", "metadata provider", "movie db", "themoviedb", "token"]),
    SettingsField(panel: "metadata", label: "TVDB API key", keywords: ["augment", "byo key", "credentials", "enable", "reserved", "series provider", "thetvdb", "toggle", "token", "v4"]),
    SettingsField(panel: "metadata", label: "TVmaze", keywords: ["air time", "enable", "episode air", "free", "network time", "timezone", "toggle"]),
    SettingsField(panel: "naming", label: "Anime episode format", keywords: ["absolute", "anime", "episode", "fansub", "naming", "token"]),
    SettingsField(panel: "naming", label: "Insert token", keywords: ["custom formats", "mediainfo", "placeholder", "quality full", "release group", "token palette"]),
    SettingsField(panel: "naming", label: "Movie file format", keywords: ["filename", "film", "format", "movie", "naming", "token"]),
    SettingsField(panel: "naming", label: "Movie folder format", keywords: ["film", "folder", "format", "movie title", "naming", "token"]),
    SettingsField(panel: "naming", label: "Rename files", keywords: ["file names", "organize", "rename", "renaming", "toggle"]),
    SettingsField(panel: "naming", label: "Replace illegal characters", keywords: ["filename", "illegal", "invalid characters", "sanitize", "special chars"]),
    SettingsField(panel: "naming", label: "Season folder format", keywords: ["folder", "format", "naming", "season", "token", "tv"]),
    SettingsField(panel: "naming", label: "Series edition folders", keywords: ["edition", "jellyfin", "plex", "show folder", "token", "version"]),
    SettingsField(panel: "naming", label: "Series folder format", keywords: ["folder", "format", "naming", "series title", "token", "tv"]),
    SettingsField(panel: "naming", label: "Standard episode format", keywords: ["episode", "file", "naming", "sxxexx", "token", "tv"]),
    SettingsField(panel: "profiles", label: "Custom Formats", keywords: ["cf score", "custom format score", "points", "scoring", "stepper", "trash"]),
    SettingsField(panel: "profiles", label: "Delete", keywords: ["confirm", "delete profile", "remove", "trash"]),
    SettingsField(panel: "profiles", label: "Duplicate", keywords: ["clone", "copy", "duplicate profile"]),
    SettingsField(panel: "profiles", label: "Edit Groups", keywords: ["equal rank", "group qualities", "merge", "quality group", "webdl webrip"]),
    SettingsField(panel: "profiles", label: "Filter by kind", keywords: ["all", "anime", "media kind", "movies", "series", "tab"]),
    SettingsField(panel: "profiles", label: "Language", keywords: ["audio language", "foreign", "italian", "multi", "original language", "reject language"]),
    SettingsField(panel: "profiles", label: "Min CF Increment", keywords: ["beat", "custom format", "minimum increment", "score delta", "upgrade format score"]),
    SettingsField(panel: "profiles", label: "Min CF Score", keywords: ["custom format score", "min_format_score", "minimum", "reject", "threshold"]),
    SettingsField(panel: "profiles", label: "New profile", keywords: ["+ new", "add", "create", "quality profile"]),
    SettingsField(panel: "profiles", label: "Profile kind", keywords: ["anime", "media type", "movie", "scope", "series"]),
    SettingsField(panel: "profiles", label: "Profile name", keywords: ["label", "quality profile name", "rename", "title"]),
    SettingsField(panel: "profiles", label: "Qualities", keywords: ["allowed qualities", "bluray", "ladder", "rank", "remux", "reorder", "resolution", "webdl"]),
    SettingsField(panel: "profiles", label: "Scored only", keywords: ["custom format", "filter", "hide zero", "nonzero", "only scored"]),
    SettingsField(panel: "profiles", label: "Search profiles", keywords: ["filter", "find", "lookup", "name", "quality profile"]),
    SettingsField(panel: "profiles", label: "Upgrade Until", keywords: ["ceiling", "cutoff", "quality cutoff", "stop upgrading", "until quality"]),
    SettingsField(panel: "profiles", label: "Upgrade Until CF Score", keywords: ["ceiling", "custom format", "cutoff format score", "score limit", "stop upgrade"]),
    SettingsField(panel: "profiles", label: "Upgrades", keywords: ["allowed", "better release", "replace file", "upgrade allowed"]),
    SettingsField(panel: "qualitydefinitions", label: "Preview for", keywords: ["episode", "gb per file", "minutes", "movie", "preview", "runtime"]),
    SettingsField(panel: "qualitydefinitions", label: "Reset to defaults", keywords: ["arr defaults", "reset", "restore", "revert", "trash"]),
    SettingsField(panel: "qualitydefinitions", label: "Size limits", keywords: ["file size", "max", "mb per minute", "min", "preferred", "range", "size range"]),
    SettingsField(panel: "releasefilters", label: "Rejected terms", keywords: ["banned", "blocklist", "ignored words", "must not contain", "regex", "reject", "release profile"]),
    SettingsField(panel: "releasefilters", label: "Required terms", keywords: ["match", "must contain", "preferred words", "release profile", "required", "whitelist"]),
    SettingsField(panel: "releasefilters", label: "Test a release title", keywords: ["check release name", "match test", "preview", "try", "verdict", "would be grabbed"]),
    SettingsField(panel: "roots", label: "Add root folder", keywords: ["directory", "library folder", "media path", "new folder", "root path", "storage"]),
    SettingsField(panel: "roots", label: "Auto-op defaults", keywords: ["add default", "auto", "default root", "kind tier", "pinned", "star"]),
    SettingsField(panel: "roots", label: "Import mode", keywords: ["copy", "debrid", "hardlink", "move", "per root", "rclone", "symlink"]),
    SettingsField(panel: "roots", label: "Path", keywords: ["directory", "folder path", "location", "mount", "root"]),
    SettingsField(panel: "roots", label: "Root folders", keywords: ["anime", "disk space", "mount", "movies", "movies-4k", "path", "tier", "tv"]),
    SettingsField(panel: "security", label: "App API key", keywords: ["api", "credential", "regenerate", "reveal", "rotate", "secret", "token", "x-api-key"]),
    SettingsField(panel: "system", label: "Commands", keywords: ["activity", "background jobs", "in-flight", "queue", "running"]),
    SettingsField(panel: "system", label: "Library metadata", keywords: ["air times", "anidb", "anime ids", "enrichment", "refresh", "run all", "tmdb", "tvmaze"]),
    SettingsField(panel: "system", label: "Scheduled tasks", keywords: ["command", "cron", "import poll", "interval", "jobs", "rss sync", "run now"]),
    SettingsField(panel: "appearance", label: "Accent theme", keywords: ["aurora", "brand", "color", "colour", "look", "swatch", "theme"]),
    SettingsField(panel: "trash", label: "Auto-sync interval", keywords: ["automatic update", "cadence", "daily", "off", "schedule", "trash guides refresh", "weekly"]),
    SettingsField(panel: "trash", label: "Avoid Raws / LQ", keywords: ["anime", "low quality", "nudge", "penalise", "raw", "score down"]),
    SettingsField(panel: "trash", label: "Custom Formats", keywords: ["catalog", "cf", "guide formats", "scoring", "specs", "trash cf"]),
    SettingsField(panel: "trash", label: "Overrides & Conflicts", keywords: ["conflict", "diff", "divergence", "local vs guide", "override", "reset to guide"]),
    SettingsField(panel: "trash", label: "Prefer Dual-Audio", keywords: ["anime", "dual audio", "japanese english", "nudge", "score up"]),
    SettingsField(panel: "trash", label: "Prefer Dubs (English)", keywords: ["anime", "dubbed", "english dub", "nudge", "score up"]),
    SettingsField(panel: "trash", label: "Prefer Uncensored", keywords: ["anime", "no censorship", "nudge", "score up", "uncensored"]),
    SettingsField(panel: "trash", label: "Presets", keywords: ["bundle", "preset", "quick setup", "template"]),
    SettingsField(panel: "trash", label: "Profiles", keywords: ["cutoff", "guide profiles", "import profile", "quality profile", "recommended", "trash"]),
    SettingsField(panel: "trash", label: "Sync now", keywords: ["fetch", "manual sync", "pull trash", "refresh", "update guide"]),
]
